# Generated by Django 4.1.5 on 2023-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewAsia', '0003_contactmodel_alter_viewimages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploadedimg')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
