# Generated by Django 4.1.5 on 2023-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewAsia', '0004_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
